### PR TITLE
Require jupyter-packaging as setup deps

### LINKED ISSUE #159: Installation will not work if assets are not found and jupyter-packaging is not installed
If JavaScript build assets are not there and if jupyter-packaging is not installed, the installation will be broken without any error message. This is due to the following try-except:

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/setup.py#L72-L84

### LINKED ISSUE #167: setup.py ignoring ImportErrors
Hi,

Why do we ignore import errors here: https://github.com/jupyterlab/extension-cookiecutter-ts/blob/ae2a726a1dc6d83016de7b471ae0d40b878d59fc/%7B%7Bcookiecutter.python_name%7D%7D/setup.py#L83 It would seem like if we can't import, we should fail.

I raise this, as I couldn't figure out https://github.com/deshaw/jupyterlab-execute-time/issues/44 for the longest time, and it turned out to be because `jupyter-packaging` was not installed in my release environment correctly. Instead of failing, it released.

Thanks!

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #159
Fixes #167 

The data files should not be conditionned on anything => jupyter packaging needs to be installed as setup dependencies.

### CODE REVIEW

**Comment by fcollonval** [comment]
The real problem is the command `jupyter labextension develop . --overwrite`

It raises:

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    raise e
  File "setup.py", line 9, in <module>
    from jupyter_packaging import get_data_files, npm_builder, wrap_installers
ModuleNotFoundError: No module named 'jupyter_packaging'
An error occured.
FileNotFoundError: The Python package `.` is not a valid package, it is missing the `setup.py` file.
```

as it calls command such `python setup.py --name`. So I think we need either `jupyterlab` to require `jupyter-packaging` or to mock it to succeed at handling the `labextension develop`.

@blink1073 @jtpio @krassowski what do you think?

**Comment by ktaletsk** [comment]
I would like to add that current changes in this PR also fix another issue for me: when trying to manually build python source archive and a wheel  with `python setup.py sdist bdist_wheel` and then install from the wheel (`pip install myextension-0.1.0-py3-none-any.whl`) server- and labextensions are not getting installed.

On [3.0](/jupyterlab/extension-cookiecutter-ts/tree/3.0), this manual build process gives:
```bash
$ jupyter server extension list
Config dir: /home/jovyan/.jupyter

Config dir: /opt/conda/etc/jupyter
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.16 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter

$ jupyter labextension list
JupyterLab v3.0.16
```
and on the [fix/setup_py](/fcollonval/extension-cookiecutter-ts/tree/fix/setup_py):
```bash
$ jupyter server extension list
Config dir: /home/jovyan/.jupyter

Config dir: /opt/conda/etc/jupyter
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.16 OK
    myextension enabled
    - Validating myextension...
      myextension 0.1.0 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter

$ jupyter labextension list
JupyterLab v3.0.16
/opt/conda/share/jupyter/labextensions
        myextension v0.1.0 enabled OK (python, myextension)
```

**Comment by fcollonval** [comment]
Here is a new version that raises an error when `jupyter-packaging` except when introspecting package name or version (what is used by some jupyter lab build commands).

> I used logging to print the warning on stderr. So it is not blocking introspection that is catching stdout.

**Review by blink1073 — APPROVED** [review]
LGTM, thank you!

**Comment by fcollonval** [comment]
@ktaletsk @mlucool would you mind testing the latest version to check that it solves your issues?

**Comment by ktaletsk** [comment]
@fcollonval I confirm that it solves my issue, thank you for solving it!

**Comment by mlucool** [comment]
This works great - thanks!

**Pull request merged**
