### PR TITLE
Update to jupyterlab 4.0.0b0

### PR DESCRIPTION
**Pull request by brichet**
This PR updates the extension-cookiecutter to `jupyterlab>=4.0.0a37` (with yarn3).

It includes the changes of https://github.com/jupyterlab/extension-cookiecutter-ts/pull/291 by @trungleduc.

It also adds some missing *devDependencies* which should allow `yarn install` using `nodeLinker: pnpm`.

### CODE REVIEW

**Comment by jtpio** [comment]
> some missing _devDependencies_

Do you know if that was because the cookiecutter setup was making explicit use of them, and expecting these dev dependencies to be installed via another dependency? For example via `@jupyterlab/builder`.

**Comment by brichet** [comment]
> Do you know if that was because the cookiecutter setup was making explicit use of them, and expecting these dev dependencies to be installed via another dependency? For example via `@jupyterlab/builder`.

No, it is not explicit use.
- `react` is a peer dependency of `@rjsf/utils`, imported via `@jupyterlab/settingregistry`.
- `@type/json-schema` is also expected by `@rjsf/utils`, but I don't really understand why, for me it should be included in the package.
- `yjs` is a peer dependency of `y-protocol`
- the others are necessary to build the extension (probably for webpack): https://github.com/jupyterlab/jupyterlab/blob/a3a0e3e7abf75e53810ed7ff8037c439cbb07697/buildutils/src/ensure-repo.ts#L71-L81. But it seems that not all of them were necessary.

**Review by fcollonval — APPROVED** [review]
Thanks @brichet

**Comment by jtpio** [comment]
Still wondering why we need to explicitly list these `devDependencies`.

> the others are necessary to build the extension (probably for webpack): https://github.com/jupyterlab/jupyterlab/blob/a3a0e3e7abf75e53810ed7ff8037c439cbb07697/buildutils/src/ensure-repo.ts#L71-L81. But it seems that not all of them were necessary.

Normally the extension code should not have to care about these webpack dependencies, since they are already dependencies of `@jupyterlab/builder`.

**Comment by jtpio** [comment]
Asking because the same list of `devDependencies` can also be found in the extension template: https://github.com/jupyterlab/extension-template

**Comment by fcollonval** [comment]
This is due to stricter check of pnpm packager about dependency specifications.

**Comment by jtpio** [comment]
Maybe these `devDependencies` could be put behind a "use pnpm?" copier flag, to remove noise for extensions staying on the default `jlpm`?

**Comment by brichet** [comment]
> Maybe these `devDependencies` could be put behind a "use pnpm?" copier flag, to remove noise for extensions staying on the default `jlpm`?

Strict control also applies to the use of node-modules. 
By the way, extension-cookiecutter-ts generate an extension using node-modules:
https://github.com/jupyterlab/extension-cookiecutter-ts/blob/0ba10b8e268135a9c4c0283c8498a5d8f4a62c8f/%7B%7Bcookiecutter.python_name%7D%7D/.yarnrc.yml#L3

**Pull request merged**
