### PR TITLE
Use `maintainer-tools` base setup action on CI

### PR DESCRIPTION
**Pull request by jtpio**
Use the `base-setup` action from the `maintainer-tools` repo: https://github.com/jupyterlab/maintainer-tools#base-setup

Similar to https://github.com/jupyterlab/jupyterlab/pull/11595

### CODE REVIEW

**Comment by fcollonval** [comment]
LGTM @jtpio 

I restarted the CI just to be sure the error on Windows was only related to the network timeout.

**Comment by jtpio** [comment]
Thanks. Some checks are now failing due to the latest 4.0 pre-release, opened https://github.com/jupyterlab/extension-cookiecutter-ts/pull/193 to fix it.

**Comment by jtpio** [comment]
CI is now passing.

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Pull request merged**
