### PR TITLE
Add `yarn-error.log` to `.gitignore`

### PR DESCRIPTION
**Pull request by joaopalmeiro**
If an error occurs when running a script through `jlpm` (due to a missing comma between scripts), for example, Yarn generates an error log file. So, with this addition, this file is also ignored.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Perhaps just `*.log`?

**Comment by joaopalmeiro** [comment]
Updated!

**Review by fcollonval — APPROVED** [review]
Thanks @joaopalmeiro

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0

**Pull request merged**
