### PR TITLE
Fix binder install

### PR DESCRIPTION
**Pull request by goanpeca**
The docs point to using

https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#build-and-install-the-extension-for-development

`pip install -e .` and `jupyter labextension develop --overwrite .`

But the second command is missing in the binder `postBuild`

### CODE REVIEW

**Comment by fcollonval** [comment]
As stated in the mentioned link, the develop command allows _to create a symbolic link from JupyterLab to our source directory_. By default with `pip install -e`, the files will be copied not symlinked. So for binder this is ok not to run the develop command.

**Comment by goanpeca** [comment]
I made a PR the last days because this extension (https://github.com/deshaw/jupyterlab-execute-time)  was not working on binder (nor locally for dev mode) if I did `pip install -e .`

:-| 

Do I need to install jupyter-packaging for `pip install -e .` to do the right thing ?

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/setup.py#L72

Is that is the case then we would need to add that to `environment.yml`  since it is not longer on `install-requires` ?

**Review by blink1073 — APPROVED** [review]
Yes, this makes sense because `pip` does not handle `data_files` in develop mode.

**Comment by fcollonval** [comment]
Ho yep sorry @goanpeca I forgot that now `jupyter-packaging` is optional. So thanks @blink1073 for merging this one.

**Pull request merged**
