### PR TITLE
Update gitignore files and add JupyterLab3 keyword

### LINKED ISSUE #106: Enfoce JupyterLab3 keyword for JupyterLab 3
I have read @ianhi suggesting using Trove classification https://github.com/pypa/trove-classifiers/blob/master/src/trove_classifiers/__init__.py.

As workaround, we could also enforce jupyterlab3 as keyword that would make it clear that we don't search on server side components of former jupyterlab2 extensions.

```bash
pip search jupyterlab3
quirkshop-jlab3-react (0.1.0)  - Quirkshop JupyterLab3 React
```

```
pip search jupyterlab
jupyterlab (2.2.9)                            - The JupyterLab notebook server extension.
  INSTALLED: 2.3.0a0
  LATEST:    2.2.9
jupyterlab-server (1.2.0)                     - JupyterLab Server
  INSTALLED: 1.2.0 (latest)
jupyterlab-wipp (0.3.0)                       - WIPP integratio
...
```

### PR DESCRIPTION
**Pull request by goanpeca**
Related to #106

### CODE REVIEW

**Review by echarles — APPROVED** [review]
LGTM. Thx @goanpeca

**Comment by jasongrout** [comment]
Following the pattern at https://github.com/pypa/trove-classifiers/blob/master/src/trove_classifiers/__init__.py#L105, should we do `"Framework :: JupyterLab :: 3"`, or perhaps `"Framework :: Jupyter :: JupyterLab :: 3"`?

**Comment by goanpeca** [comment]
Sure why not, but what is optional and needs to exist? Or which one can we use right away?

**Comment by jasongrout** [comment]
Good question. I don't know if we can use classifiers that aren't officially listed. More about the application process over at https://github.com/jupyterlab/extension-cookiecutter-ts/issues/106#issuecomment-716037510 - I think this can probably be done in parallel with a keyword (in fact, having a keyword would make it easier to find packages that would be on the application for the trove classifier)

**Comment by goanpeca** [comment]
@jasongrout will work on requesting the trove classifier as you suggested on #106.

This one should be good to merge anyway while the other part is done. As you rightly pointed out, 

>having a keyword would make it easier to find packages that would be on the application for the trove classifier

So we can merge :)

**Comment by echarles** [comment]
Thx @goanpeca Merged.

**Pull request merged**
