### PR TITLE
Integrate theme cookiecutter

### PR DESCRIPTION
**Pull request by fcollonval**
To reduce maintenance burden this merge https://github.com/jupyterlab/theme-cookiecutter

The cookiecutter variables have been changed to first request the type of extension using a enumeration: frontend, server or theme.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

> To reduce maintenance burden this merge https://github.com/jupyterlab/theme-cookiecutter

+1, since the theme cookiecutter can easily get out of sync and doesn't necessarily benefit from the improvements made to the ts cookiecutter here (for example CI and releaser config).

Some follow-up steps that come to mind:

- Archive: https://github.com/jupyterlab/theme-cookiecutter
- Update the extension tutorial
- Update the apod repo

**Comment by fcollonval** [comment]
@jtpio would it be ok to move forward with this?

**Review by jtpio — APPROVED** [review]
Looks good, thanks!

**Comment by jtpio** [comment]
> Some follow-up steps that come to mind:

Let's open the corresponding issues to keep track of these steps.

**Pull request merged**
