### PR TITLE
Update to JupyterLab 1.0

### PR DESCRIPTION
**Pull request by jtpio**
Maybe worth waiting for the official 1.0 release before merging.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!  Yeah, we typically do this as part of the release process of jlab itself: https://github.com/jupyterlab/jupyterlab/blob/master/RELEASE.md#post-prerelease-checklist

**Comment by jtpio** [comment]
OK good.

Will keep this one open then, so it can serve as a reference for those already targeting JLab 1.0 in their third-party extensions.

**Comment by blink1073** [comment]
:+1:

**Comment by jtpio** [comment]
Closing, replaced by https://github.com/jupyterlab/extension-cookiecutter-ts/pull/43

**Comment by jasongrout** [comment]
Ah, sorry, I didn't see your PR!

**Comment by jtpio** [comment]
No problem!

**Pull request closed without merging**
