### PR TITLE
Add Python 3.10 trove classifier

### PR DESCRIPTION
**Pull request by jtpio**
Now that Python 3.10 is out.

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio 

Should we start testing multiple Python version in the CI?

**Comment by jtpio** [comment]
I guess we could, although we probably don't need the full 3.6 - 3.10 range, maybe just the last 3 stable versions?

**Comment by bollwyvl** [comment]
There are _days_ left until python 3.6 is EOL. For a new-start project, I'd drop that like it's hot.

Running against the lowest-advertised version is clutch, though, so perhaps `["3.7", "3.10"]`?

**Comment by jtpio** [comment]
Thanks!

Will follow-up with this in a separate PR.

**Pull request merged**
