### PR TITLE
Relax `.prettierignore` to format the root `package.json` as well

### PR DESCRIPTION
**Pull request by joaopalmeiro**
Another possibility is to remove the `**/package.json` line, as the other patterns cover most cases, if I'm correct.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Perhaps add a prettier plugin to do ordering, as there is a "right" (or at
least conventional) order for that specific JSON.

**Comment by joaopalmeiro** [comment]
> Perhaps add a prettier plugin to do ordering, as there is a "right" (or at least conventional) order for that specific JSON.

Sounds like a great idea to me! 

I think we should first discuss this topic in an issue because, at least for me, there are some open questions:

- Which package to use for sorting? I use [sort-package-json](https://github.com/keithamus/sort-package-json) as a CLI, but there's also an ESLint plugin with it, as well as one for Prettier.
- What should be the order for the `jupyterlab` nested field? The one in [this file](https://github.com/jupyterlab/jupyterlab/blob/master/builder/metadata_schema.json) or alphabetical?

What do you think?

**Comment by krassowski** [comment]
Is any of the proposed dependencies for sorting coming from an official organization that takes care of maintenance?

**Comment by joaopalmeiro** [comment]
> Is any of the proposed dependencies for sorting coming from an official organization that takes care of maintenance?

Sorry, I'm not sure what you mean by "official organization", but I don't think so (at least the one I know and mentioned above).

**Comment by krassowski** [comment]
I mean something like https://github.com/eslint/eslint-plugin-markdown where the maintenance and releases are taken care by the eslint team. If there was one like this it would be a no-brainier to add it. Otherwise we need to ask a question: will the extra dependency bring enough benefit to justify the larger dependency tree with more points of failure?

**Comment by joaopalmeiro** [comment]
> I mean something like https://github.com/eslint/eslint-plugin-markdown where the maintenance and releases are taken care by the eslint team. If there was one like this it would be a no-brainier to add it. Otherwise we need to ask a question: will the extra dependency bring enough benefit to justify the larger dependency tree with more points of failure?

Thanks for the clarification, @krassowski! So no, sort-package-json is not maintained by an official organization, as far as I know. Anyway, from the statistics on npm and GitHub, this package is heavily used (arguable) and is in active development, in my perspective.

Just to complement, I also had a look at [fixpack](https://github.com/henrikjoreteg/fixpack) and [npm-package-json-lint](https://github.com/tclindner/npm-package-json-lint) (particularly the [prefer-property-order rule](https://npmpackagejsonlint.org/docs/rules/package-json-properties/prefer-property-order)), but sort-package-json seems to be the best option for sorting package.json files (as a CLI or via ESLint/Prettier), if this possibility makes sense for this repo.

EDIT: I noticed now that sort-package-json is used in `@jupyterlab/buildutils` as a [dependency](https://github.com/jupyterlab/jupyterlab/blob/fc68c4d37dc925e3ceed54a9cf09c8370c78a845/buildutils/package.json#L57).

**Review by fcollonval — APPROVED** [review]
Thanks @joaopalmeiro

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0

**Pull request merged**
