### PR TITLE
Fix update galata action

### LINKED ISSUE #258: update-snapshots fails (3.0) due to missing jupyterlab setup
```
  set -eux
  jlpm
  python -m pip install .
  shell: /usr/bin/bash -e {0}
+ jlpm
/home/runner/work/_temp/883e7265-4e7f-4365-b0ea-df9e52ade86c.sh: line 2: jlpm: command not found
Error: Process completed with exit code 127.
```

Example https://github.com/jupyterlab/ui-profiler/actions/runs/3722798618/jobs/6313896572#logs

Ideally we would test actions.

### PR DESCRIPTION
**Pull request by krassowski**
Fixes #258

### CODE REVIEW

**Comment by krassowski** [comment]
Well, that did not work, I still get `error Command "test:update" not found.`: https://github.com/jupyterlab/ui-profiler/actions/runs/3722914299/jobs/6314104448. Any ideas?

**Comment by krassowski** [comment]
Ok, it was fine I just needed to rebase - thanks for the suggestion @fcollonval.

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.0

**Pull request merged**
