### PR TITLE
Update sequential commands to use `run-s`

### PR DESCRIPTION
**Pull request by joaopalmeiro**
For consistency purposes, if you agree, given that the `npm-run-all` package is a dev dependency and used in the `watch` command.

### CODE REVIEW

**Comment by krassowski** [comment]
Is there a benefit of using `run-s` over `&&`? I can see a potential downside because if we add commands with multiple arguments we would need to escape spaces, right?

**Comment by joaopalmeiro** [comment]
> Is there a benefit of using `run-s` over `&&`? I can see a potential downside because if we add commands with multiple arguments we would need to escape spaces, right?

From my perspective, the benefits are consistency (although `run-p` has the extra benefit of being cross-platform) and shorter commands.

Yes, we would have to enclose the script in quotes (e.g., `"lint": "run-s stylelint prettier \"eslint --debug\""`), but that doesn't seem an issue to me because of how the commands are prepared.

**Review by fcollonval — COMMENTED** [review]
I'm not a big fan of this one because I think the `&&` syntax is known by more people than `run-s` command. So beginners will have yet another think to learn.

**Comment by joaopalmeiro** [comment]
All right! What should I do about this PR? Or should I just wait for it to be closed and I don't need to do anything else?

**Comment by fcollonval** [comment]
Thanks for the ping @joaopalmeiro  - as nobody else commented, I'll close it. If somebody has additional arguments, we can always reboot this.

**Pull request closed without merging**
